### ISSUE TITLE
Home configurations on other systems not working

### ISSUE THREAD

**Issue by buxel** [suderman/nixos#1]
Hello!

I'm currently learning nix and browsing your repo is really insightful. Thank you for sharing it!

For the first time i decided to try home-manager following your setup but i have stumbled upon an issue.
I added the required files `./configurations/buxel/{base, home}.nix` and updated the config to include a profile for my user:

```nix
      homeConfigurations = {
        # umbra = mkUser ./configurations/umbra; /* system = "x86_64-darwin" */
        buxel = mkUser ./configurations/buxel ; /* system = "x86_64-linux" */
      };
```

If i run the repl and wuld like to inspect the homeConfiguration, there is an error

```
       error: attribute 'system' missing

       at /nix/store/sd1h6viq28m18xlixsr3sminp8j5pm3k-source/flake.nix:129:23:

          128|         extraSpecialArgs = { inherit inputs outputs; base = import (path + /base.nix); };
          129|         pkgs = mkPkgs extraSpecialArgs.system;
             |                       ^
          130|         modules = [
```

I managed to mess it up a little more by trying to add a line  `inherit (extraSpecialArgs.base) system;` , but this just brought me to a different error which made me realize, i accidently passed `system` to `homeManagerConfiguration`.

It feels like an easy fix but the nix language is still very verbose to me.

**Comment by suderman** [comment]
Hi there,

I goofed in my mkUser function and this line:

`pkgs = mkPkgs extraSpecialArgs.system;`

should have been:

`pkgs = mkPkgs extraSpecialArgs.base.system;`

...but really, it's because the homeConfigurations block is meant for use with standalone home-manager and this isn't something I currently use. At one point, I thought I might have a mix of NixOS systems and traditional systems with home-manager on top, but I've ended up just converting everything to NixOS instead. :-)

Enjoy learning nix... it's a journey!

**Comment by buxel** [comment]
This is exactly my usecase. I would like to create a home-manager config on the Debian system I use to deploy/manage my other systems. I totally get the pull to convert everything to NixOS! Everything else just feels wrong and dirty 😄 

But... one step at a time! I already tried replacing that line with `pkgs = mkPkgs extraSpecialArgs.base.system;` before but since this produced even more verbose errors, I thought it was wrong.

**EDIT** it was the cache/substituters config i have not updated yet! Repl works now :)
I assume once the repl can evaluate my config, I will be able to switch to it in the standalone home-manager i have already installed, right?

**EDIT2** i was able to build and activate the home configuration via `nix build '.#homeConfigurations."buxel".activationPackage'` and running `./result/activate`. It feels a little clunky doing this every time I make a change and since it is not in the default home-manager configuration directory it is also not picked up by it. Do you have any poitners to a smoother workflow?


(i will leave the error log for reference/google/another poor soul to find here)
```
nix-repl> homeConfigurations.buxel
{ activation-script = «error: error:
       … from call site

         at /nix/store/m5wxwjc2axqsywb1w5l8sqi5kx3pqr5s-source/modules/default.nix:39:12:

           38|
           39|   module = showWarnings (
             |            ^
           40|     let

       … while calling 'showWarnings'

         at /nix/store/m5wxwjc2axqsywb1w5l8sqi5kx3pqr5s-source/modules/default.nix:18:18:

       error:
       Failed assertions:
       - A corresponding Nix package must be specified via `nix.package` for generating
       nix.conf.»; activationPackage = «error: error:
       … from call site

         at /nix/store/m5wxwjc2axqsywb1w5l8sqi5kx3pqr5s-source/modules/default.nix:39:12:

       - A corresponding Nix package must be specified via `nix.package` for generating
       nix.conf.»; config = «error: error:
       … from call site

         at /nix/store/m5wxwjc2axqsywb1w5l8sqi5kx3pqr5s-source/modules/default.nix:39:12:

           38|
           39|   module = showWarnings (
             |            ^
           40|     let
  
       error:
       Failed assertions:
       - A corresponding Nix package must be specified via `nix.package` for generating
       nix.conf.»; newsDisplay = "notify"; newsEntries = [ ... ]; options = «error: error:
       … from call site

         at /nix/store/m5wxwjc2axqsywb1w5l8sqi5kx3pqr5s-source/modules/default.nix:39:12:

           38|
           39|   module = showWarnings (
             |            ^
           40|     let

       error:
       Failed assertions:
       - A corresponding Nix package must be specified via `nix.package` for generating
       nix.conf.»; pkgs = «error: error:
       … from call site

         at /nix/store/m5wxwjc2axqsywb1w5l8sqi5kx3pqr5s-source/modules/default.nix:39:12:

           38|
           39|   module = showWarnings (
             |            ^
           40|     let

       error:
       Failed assertions:
       - A corresponding Nix package must be specified via `nix.package` for generating
       nix.conf.»; }
```

**Comment by suderman** [comment]
> **EDIT2** i was able to build and activate the home configuration via `nix build '.#homeConfigurations."buxel".activationPackage'` and running `./result/activate`. It feels a little clunky doing this every time I make a change and since it is not in the default home-manager configuration directory it is also not picked up by it. Do you have any poitners to a smoother workflow?

Early on I was separating my nixos config from my home-manager config and activating as two separate steps, hence the homeConfigurations definition that still exists in my flake. 

However, your path looks pretty different from mine. I remember installing and using the home-manager CLI tool to switch my home-manager configuration (I wasn't running nix build or activate scripts manually like that). It wasn't long before I just went full nixos and moved my standalone home-manager config into a nixos module, and I haven't used the home-manager tool in a long time now. Sorry!

**Comment by buxel** [comment]
Then i probably goofed up my standalone home-manager setup. I added a devShell to access the tools in the flake and this is good enough for now.

For reference, i appended this to `flake.nix`

```nix
devShells = let 
        system = "x86_64-linux";
        pkgs = mkPkgs system;
      in  {
        "${system}".default = pkgs.mkShell { 
          buildInputs = [ 
            inputs.agenix.packages."${system}".default 
            pkgs.nixos-cli
          ]; 
        };
      };
```
