### ISSUE TITLE
Random logouts with OCIS

### ISSUE THREAD

**Issue by buxel** [suderman/nixos#10]
Hi @suderman 

After a long break I have time to tinker again. I was planning to use OCIS with my wife after evaluating the wife-acceptance-factor myself on multiple devices. 
Have you also noticed seemingly random logouts and/or frequent prompts to login again? I'm not sure if it is connected but occasionally when I open it in a browser, it will show an HTTP basic auth popup. My OCIS credentials do not work here and after closing it, OCIS will ask me to re-authenticate via the OCIS login form.

Needless to say, the WAF is pretty low in this state :D

**Comment by suderman** [comment]
I've noticed this too. :-/ It's on the backburner for me, as my current usage of OCIS is low and I'm kinda waiting for v5 to be released before diving in again.

https://github.com/owncloud/ocis/releases

**Comment by buxel** [comment]
no worries, looking forward to v5!

**Comment by buxel** [comment]
@suderman  To add another observation: when running via tailscale (before the networking refactor) it only happened occasionally. Now, after updating my config, logging into OCIS is not possible anymore (no pressure, just adding a data point).

I like reproducible errors more than random ones, so it is kind of an improvement 😆

EDIT:

Another lead: i was skimming journalctl when this caught my eye after logging in:

```
Feb 25 12:07:34 bender docker-ocis-start[1778897]: {"level":"warn","service":"frontend","pkg":"rhttp","traceid":"abc1293012d501059ce210042f3bf6b7","time":"2024-02-25T19:07:34.521957164Z","line":"github.com/cs3org/reva/v2@v2.16.4-0.20231220070538-82b93f6a66bc/internal/http/interceptors/auth/auth.go:230","message":"core access token not set"}

and

Feb 25 12:07:34 bender ed8e248fd3ba[1365603]: {"level":"error","service":"proxy","error":"failed to verify access token: Get \"https://cloud.bender/.well-known/openid-configuration\": dial tcp: lookup cloud.bender on 100.100.100.100:53: no such host","authenticator":"oidc","path":"/ocs/v1.php/cloud/user","time":"2024-02-25T19:07:34.521736243Z","line":"github.com/owncloud/ocis/v2/services/proxy/pkg/middleware/oidc_auth.go:165","message":"failed to authenticate the request"}
```

`dial tcp: lookup cloud.bender on 100.100.100.100:53` 🤔 AFAIK, the container is not able to use tailscale DNS, is it?

My `resolv.conf` on `bender` uses tailscale's nameserver. Oracle also somehow got into it.
```
/etc/nixos (upstream-adaptions*) » cat /etc/resolv.conf                                                                                                                                                                                                                                                me@bender
# Generated by resolvconf
search vcn01241459.oraclevcn.com
nameserver 100.100.100.100
options edns0
```

Checking blocky locally on the machine seems to work fine
```
/etc/nixos (upstream-adaptions*) » dig @127.0.0.1 cloud.bender                                                                                                                                                                                                                                         me@bender

; <<>> DiG 9.18.19 <<>> @127.0.0.1 cloud.bender
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 64866
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;cloud.bender.                  IN      A

;; ANSWER SECTION:
cloud.bender.           3600    IN      A       100.101.148.41

;; Query time: 0 msec
;; SERVER: 127.0.0.1#53(127.0.0.1) (UDP)
;; WHEN: Sun Feb 25 13:54:11 MST 2024
;; MSG SIZE  rcvd: 46
```

inside the container it fails:
```
/var/lib/ocis $ nslookup cloud.bender 
Server:         100.100.100.100
Address:        100.100.100.100:53

** server can't find cloud.bender: NXDOMAIN
```

the OCIS container could look up it's own host hostname using blocky running on it
```
nslookup bender 100.101.148.41:53
Server:         100.101.148.41:53
Address:        100.101.148.41:53

Non-authoritative answer:

Non-authoritative answer:
Name:   bender
Address: 100.101.148.41
```

a little verbose just to resolve the local hostname ... i feel like there has to be a better way but this is where my search ends for today 😴

**Comment by suderman** [comment]
Thanks for this, the timing of when it stopped working actually does make sense now that I think about it...

**Comment by suderman** [comment]
My logs expressed trust issues with the self-signed certificate which was apparently blocking my ability to login at all. I [changed](https://github.com/suderman/nixos/commit/608e7fce0f8da0e34a8c60d3e8e4fb1f8fdfb09b) a environment variable `OCIS_INSECURE = "true";` which finally let me in. Too soon to know if this also helps the original random logouts issue.

**Comment by buxel** [comment]
you are on fire! i saw that you just implemented the reverse proxy idea for public services 😄 

I will keep an eye on OCIS after installing the root ca on all my devices

**Comment by buxel** [comment]
working fine on 3 devices - closing :)
