### ISSUE TITLE
Blocky fails to start after reboot

### ISSUE THREAD

**Issue by buxel** [suderman/nixos#12]
Sorry to bug you with another one. I played with blocky on my VPS, which i usually never reboot.

But yeah, I did today. Blocky fails to start when it tries to bring up the webserver. The service is in failed state and the logs show 

```
Error: can't start server: start http listener on 100.101.148.41:4000 failed
```

Fair enough. `netstat` did not show any service on that port but as i was lazy, i just changed blocky to 4001:

```
Error: can't start server: start http listener on 100.101.148.41:4001 failed
```

Yeah... is blocky blocking itself? Maybe. I will drop some more notes when i get to do some more research (why do i always run into errors way past bedtime?).

**Comment by suderman** [comment]
Hmm, that error shows a Tailscale IP address, so I suspect this is a race condition. If systemd tries to start Blocky _before_ Tailscale, then Blocky would be attempting to listen on an IP address that doesn't (yet) exist.

**Comment by suderman** [comment]
Trying a different approach and allowing Blocky to listen on all addresses so it won't be held up by a missing IP. I've added firewall rules to filter out public traffic, similar to my approach with private routes on Traefik.

**Comment by buxel** [comment]
Seems fine now 👍
