### ISSUE TITLE
Stuck at "setting up tmpfiles" / OCIS pre-start

### ISSUE THREAD

**Issue by buxel** [suderman/nixos#14]
I have merged the latest changes after a long(ish) time not updating my server.
When applying the changes, I'm stuck at "setting up tmpfiles" with no indication of what is going wrong. I left it running in that state for ~30 minutes, hoping I'd see some error messages after a timeout.

Where could i start investigating this? I doubt it has anything to do with your "file" option from `file.nix`, since it is not that new and I'm not using it in my configuration / modules at all.

```bash
sudo nixos-rebuild --flake /etc/nixos#bender switch --verbose             130 ↵ me@bender
$ nix --extra-experimental-features nix-command flakes build --out-link /tmp/nixos-rebuild.ZLshUt/nixos-rebuild /etc/nixos#nixosConfigurations."bender".config.system.build.nixos-rebuild --verbose
$ exec /nix/store/zdryq00r24r8hcw798vlqf611s559n1n-nixos-rebuild/bin/nixos-rebuild --flake /etc/nixos#bender switch --verbose
building the system configuration...
Building in flake mode.
$ nix --extra-experimental-features nix-command flakes build /etc/nixos#nixosConfigurations."bender".config.system.build.toplevel --verbose --out-link /tmp/nixos-rebuild.evxpgd/result
$ sudo --preserve-env=NIXOS_INSTALL_BOOTLOADER -- nix-env -p /nix/var/nix/profiles/system --set /nix/store/q8h9mzidfdnjvndh322xz5f7zl9x947d-nixos-system-bender-23.11.20240301.79baff8
Using systemd-run to switch configuration.
$ sudo --preserve-env=NIXOS_INSTALL_BOOTLOADER -- systemd-run -E LOCALE_ARCHIVE -E NIXOS_INSTALL_BOOTLOADER --collect --no-ask-password --pty --quiet --same-dir --service-type=exec --unit=nixos-rebuild-switch-to-configuration --wait /nix/store/q8h9mzidfdnjvndh322xz5f7zl9x947d-nixos-system-bender-23.11.20240301.79baff8/bin/switch-to-configuration switch
activating the configuration...
[agenix] creating new generation in /run/agenix.d/4
[agenix] decrypting secrets...
decrypting '/nix/store/853pw6jpxnqjm4csh9afs51xzcgsw74z-alphanumeric-secret.age' to '/run/agenix.d/4/alphanumeric-secret'...
decrypting '/nix/store/vj76c1dj1v9p78xnczrafccyj6mpbgsz-basic-auth.age' to '/run/agenix.d/4/basic-auth'...
decrypting '/nix/store/g9603z4lnrvkpzn8yjw64k0vdpkxg460-blobfuse-yaml.age' to '/run/agenix.d/4/blobfuse.yaml'...
decrypting '/nix/store/amkx8gd976bag186a8rvny0gibwv1ksc-ca-key.age' to '/run/agenix.d/4/ca-key'...
decrypting '/nix/store/d1h05d15xdbk8cfvbdf2pbki4zrdjgay-cloudflare-env.age' to '/run/agenix.d/4/cloudflare-env'...
decrypting '/nix/store/xz65z1m8jfyh9m12i6d8y4aj6s4d0mzl-ocis-env.age' to '/run/agenix.d/4/ocis-env'...
decrypting '/nix/store/70bigv0jq7bkrvv5h8w9dp66l49g37al-password.age' to '/run/agenix.d/4/password'...
decrypting '/nix/store/mc9q62bgavxwh9f08by1cv4by5icxygf-password-hash.age' to '/run/agenix.d/4/password-hash'...
decrypting '/nix/store/3c0dfyaq6pbsrlflwk5yl833fgyqailh-rclone-conf.age' to '/run/agenix.d/4/rclone-conf'...
decrypting '/nix/store/h1wh3jm71hv9gjyn2flhydmkyy2zjxxv-restic-azure-env.age' to '/run/agenix.d/4/restic-azure-env'...
decrypting '/nix/store/z8iambp9q3d4vzmkc3w1lnka44g1rsz8-traefik-env.age' to '/run/agenix.d/4/traefik-env'...
[agenix] symlinking new secrets to /run/agenix (generation 4)...
[agenix] removing old secrets (generation 3)...
[agenix] chowning...
setting up /etc...
reloading user units for me...
setting up tmpfiles

```

I switched back to my old main branch and suddenly ran into the same issue, which perists after a reboot. Has some hidden state (gasp!) snuck in which might be causing this?

As usual, any help is highly appreciated :)

**Comment by suderman** [comment]
I've occasionally had systemd get stuck during a switch, especially if it's been a long time between reboots and/or deploys. Instead of switch, try boot and see if the rebuild is successful that way. You'll just need to restart to and try it out as a second step.

```bash
sudo nixos-rebuild --flake /etc/nixos#bender boot
```

**Comment by buxel** [comment]
Thank you, i already tried that and it... somewhat worked?

Good: `nixos deploy` works as before now
Bad: OCIS systemd service is stuck in pre-start. I tried to debug it as good as i can and ended up manually executing each step of the script. The last command, `chown -R 270:270 /var/lib/ocis` just never stops. 

The directory looks okay:
```
/etc/nixos (main*) » stat /var/lib/ocis                                                                  130 ↵ me@bender
  File: /var/lib/ocis
  Size: 88              Blocks: 0          IO Block: 4096   directory
Device: 0,32    Inode: 9716        Links: 1
Access: (0755/drwxr-xr-x)  Uid: (  270/    ocis)   Gid: (  270/    ocis)
Access: 2023-12-26 03:27:26.238689045 -0700
Modify: 2023-12-26 05:21:15.568790483 -0700
Change: 2024-03-13 12:47:47.819034631 -0600
 Birth: 2023-11-12 03:49:38.239854360 -0700
```

I'm beginning to suspect that the recursive `chown` may just take terribly long, given
- i have mounted /var/lib/ocis to a network drive
- OCIS does split up the files in a quite elaborate file/folder structure

On the other hand, it has never been giving me trouble before, so why would it now?

**Comment by suderman** [comment]
Seems like it's the chown, yeah. It can't be systemd tmpfiles rules, because the OCIS module doesn't use that.  Instead, it's just doing `mkdir -p /var/lib/ocis` which would later get mounted to the docker container if your pre-start finished. You'll need poke around with that mount and see if there are other slowdowns you can see. Maybe test with a local folder too.

**Comment by buxel** [comment]
Testing gives inconsistent results but it is most liely the (blobfuse) mount
- mountpoint is actually `/var/lib/ocis/storage`
- `sudo chown -R 270:270 /var/lib/ocis/storage/metadata` works
- `sudo chown -R 270:270 /var/lib/ocis/storage/users` hangs

I have read on the issue tracker, that chown is not working/respected. But from my understanding, it should not hang.

Considering chown was added ~2 weeks ago, it explains why it has not been a problem before. I'll keep poking it until my new NAS setup is done and i will not need blobfuse anymore. Thanks for the help!

**Comment by suderman** [comment]
Hey, FYI... I updated to OCIS 5, but I had to fix my config file. After deploying 5, it'll fail and keep restarting, so I did this:

```bash
sudo bash
cd /var/lib/ocis/config
mv ocis.yaml ocis4.yaml # backup original config
```

After a few moments, OCIS will generate a new yaml file. I stop OCIS and then open both and copy everything new to my old one (mostly "service_account" blocks). Starting up the service once again I was able to login.

```bash
systemctl stop docker-ocis
vi ocis.yaml ocis4.yaml # edit both files
mv ocis.yaml ocis5.yaml # rename the generated file so it's kept aside
mv ocis4.yaml ocis.yaml # rename the original file so it's active
chown ocis:ocis ocis.yaml # fix perms
chmod go-rw ocis.yaml
systemctl start docker-ocis
```

**Comment by buxel** [comment]
Thank you for the heads up. I've re-built my NAS and am still setting it up, so OCIS upgrade will take a while. 
I'm replacing OMV with Unraid to manage my storage. On top of that, there will be (many) NixOS LXCs doing my bidding 😁

**Comment by buxel** [comment]
took a while as we also started moving in the meantime. I successfully (at least from a first look) upgraded and thanks to your heads up without any surprises. 👍
