### ISSUE TITLE
[Bug] OCIS only works with default dataDir

### ISSUE THREAD

**Issue by buxel** [suderman/nixos#4]
In case you ever stumble upon this problem, I hope this saves you some time.

https://github.com/suderman/nixos/blob/15969aa685d71cdb34699e323462c767a6f003c9/modules/ocis/default.nix#L84C19-L84C19
If the `dataDir` is changed to e.g. `/mnt/documents`, OCIS tries to find that folder inside the container because of this line.

Sticking to the default works for me, so consider this informative, not a request to fix.

**Comment by suderman** [comment]
Thanks for pointing this out! It didn't stop me from running the container, but I realized I wasn't properly binding the directory that stores the encryption key. Explains my session issues. I think I have this sorted now. :-)
