### ISSUE TITLE
How do you manage your private ssh keys?

### ISSUE THREAD

**Issue by buxel** [suderman/nixos#7]
Hi again!

I was just wondering how your worfkow is for managing your private ssh keys. You seem have just two users, "me" and "blink" on your systems. Does that translate to two workstations allowed to ssh to your server(s)? Does "me" have the same private key on all your systems?

In the past, i just created key pairs for each system i was accessing my servers from. That would mean I'd have to add the public keys for me@laptop, me@desktop, me@other-pc. 

Have a nice weekend, enjoy the snow!

(yes, i'm reading you commit messages 😉 )

**Comment by suderman** [comment]
I don't manage my private ssh keys in an automated way. 

My `me` private key was generated on my [laptop](https://github.com/suderman/nixos/tree/main/configurations/cog) where it's used today. I also manually copied this private key to my phone for mobile ssh (but I probably should have just made a new one). The corresponding public key is automatically [deployed everywhere](https://github.com/suderman/nixos/blob/main/configurations/bootstrap/nixos/user.nix#L36C27-L36C27), so I can access all my systems from my laptop.

Although I have a `me` user deployed to all my systems, that doesn't mean they all get an ssh private key. Each system's unique ssh host key is enough to decrypt secrets with agenix (I just can't modify secrets on those systems). 

If I ever need to recover my laptop or start fresh without a backup of my home directory, I'd have to copy this original private key manually into my `~/.ssh` directory.

My `blink` public key is an older one that's not actually used by my config and could be removed.

Hope that's helpful. Snow is pretty much all gone now, but it will surely be back with a vengeance! ❄️☃️

**Comment by buxel** [comment]
thanks! then i'll just add multiple "@me@deviceXYZ" to have some redundancy in case a device is broken at some point.
alternatively, tailscale-ssh also sounds good. It still needs an initial "classic" ssh key for bootstrapping, though.
