### ISSUE TITLE
Postgres: missing `vectors.so` 

### ISSUE THREAD

**Issue by buxel** [suderman/nixos#9]
Merry Christmas! I hope you are having a great time with your family!

I had some spare time and synced with upstream (=you). Applying the configuration resulted in postgres failing. You already mentioned packaging immich is tricky...

Looks like t is missing `vectors.so` but the file is there. Could it be a permissions issue?

```
/etc/nixos (main) » sudo systemctl status postgresql.service                                                                                                                                    me@bender
× postgresql.service - PostgreSQL Server
     Loaded: loaded (/etc/systemd/system/postgresql.service; enabled; preset: enabled)
     Active: failed (Result: exit-code) since Tue 2023-12-26 03:39:06 MST; 1h 19min ago
   Duration: 2w 1d 14h 2min 49.851s
    Process: 2061981 ExecStartPre=/nix/store/2k93cwh6gd8ygd8v4z5j0lmcjaawwg4l-unit-script-postgresql-pre-start/bin/postgresql-pre-start (code=exited, status=0/SUCCESS)
    Process: 2061984 ExecStart=/nix/store/wbrijxflsv0gy8m2l39h9yn079vhla4b-postgresql-and-plugins-14.10/bin/postgres (code=exited, status=1/FAILURE)
   Main PID: 2061984 (code=exited, status=1/FAILURE)
         IP: 0B in, 0B out
        CPU: 22ms

Dec 26 03:39:06 bender systemd[1]: Starting PostgreSQL Server...
Dec 26 03:39:06 bender postgres[2061984]: [2061984] FATAL:  could not load library "/nix/store/wbrijxflsv0gy8m2l39h9yn079vhla4b-postgresql-and-plugins-14.10/lib/vectors.so": /nix/store/wbrijxflsv0gy8m2l39h9yn079vhla4b-postgresql-and-plugins-14.10/lib/vectors.so: cannot open shared object file: No such file or directory
Dec 26 03:39:06 bender postgres[2061984]: [2061984] LOG:  database system is shut down
Dec 26 03:39:06 bender systemd[1]: postgresql.service: Main process exited, code=exited, status=1/FAILURE
Dec 26 03:39:06 bender systemd[1]: postgresql.service: Failed with result 'exit-code'.
Dec 26 03:39:06 bender systemd[1]: Failed to start PostgreSQL Server.
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
/etc/nixos (main) » stat /nix/store/wbrijxflsv0gy8m2l39h9yn079vhla4b-postgresql-and-plugins-14.10/lib/vectors.so                                                                            3 ↵ me@bender
  File: /nix/store/wbrijxflsv0gy8m2l39h9yn079vhla4b-postgresql-and-plugins-14.10/lib/vectors.so -> /nix/store/1z0f7np703hb9kqw1y9yaki6ik81nqwn-pgvecto-rs-0.1.11/lib/vectors.so
  Size: 76              Blocks: 8          IO Block: 4096   symbolic link
Device: 0,30    Inode: 2050601     Links: 2
Access: (0777/lrwxrwxrwx)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2023-12-26 03:26:46.374489275 -0700
Modify: 1969-12-31 17:00:01.000000000 -0700
Change: 2023-12-26 03:26:44.570480285 -0700
 Birth: 2023-12-26 03:26:44.282478850 -0700
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------  
```

Any pointers would be appreciated 😄.

**Comment by buxel** [comment]
I figured out the problem: i have an aarch64 system. 😢 

[Here ](https://github.com/suderman/nixos/blob/8d0157ac2f6820de86ecdf5b21434d0279a39dfb/overlays/pkgs/pgvecto-rs.nix#L24) the platform is hardcoded so it will download the wrong package.

I'll patch it later this evening to see if it works. Can a module, which is not building from source, also be cross-platform?

**Comment by suderman** [comment]
I modified the pgvecto.rs package to use a system-specific URL when downloading the deb. I wasn't able to actually test this on aarch64, but the pre-built release is available from tensorchord, so the idea makes sense anyway. :-)

Merry Christmas!

**Comment by buxel** [comment]
Thank you :) I just merged the changes and just had to do a [minor tweak](https://github.com/buxel/nixos/commit/84124de6d3c73a9512646a95bfb9a3117025d9de#diff-a72f424a0bf09d4b456a23eb88dd8e436da6d741cc1e6d5af8b97b862c8e64fe) to add the hash for the aarch64 build. 

I'm not sure sure how the major PG version is related to the hash of pgvecto-rs, so i hijacked this bit of code to add one hash per platform.
[0001-minor-fixes-after-merge.patch](https://github.com/suderman/nixos/files/13800805/0001-minor-fixes-after-merge.patch)

**Comment by buxel** [comment]
@suderman Would you accept a PR for this?

**Comment by suderman** [comment]
Yes, except it looks like this package needs to reworked again anyway since today's Immich v1.95.0. Release filenames are in a modified format. Before it was:

- https://github.com/tensorchord/pgvecto.rs/releases/download/v0.1.11/vectors-pg14-v0.1.11-x86_64-unknown-linux-gnu.deb
- https://github.com/tensorchord/pgvecto.rs/releases/download/v0.1.11/vectors-pg14-v0.1.11-aarch64-unknown-linux-gnu.deb

...but now they're named:

- https://github.com/tensorchord/pgvecto.rs/releases/download/v0.2.0/vectors-pg14_0.2.0_amd64.deb
- https://github.com/tensorchord/pgvecto.rs/releases/download/v0.2.0/vectors-pg14_0.2.0_arm64.deb

**Comment by suderman** [comment]
@buxel FYI, I've updated [pgvecto-rs](https://github.com/suderman/nixos/blob/main/overlays/pkgs/pgvecto-rs.nix) with 0.2.0 version hashes to get [Immich 1.5.1](https://github.com/suderman/nixos/blob/main/modules/immich/default.nix) working. This one was a bumpy update...
